### ISSUE TITLE
Rustls feature

### ISSUE THREAD

**Issue by recapitalverb** [oxidizer-rs/oxidizer#13]
I am building a project that runs on Linux MUSL, so OpenSSL cannot be used. This crate would be an absolutely awesome alternative to the sqlx crate if it could use Rustls instead.

**Comment by super-horst** [comment]
@recapitalverb the past few days, I implemented a cargo feature for rustls ... Though I don't have the time to test it, hence no PR.
If you need it urgently, feel free to have a look: https://github.com/super-horst/oxidizer

**Comment by GustavoKatel** [comment]
that's amazing @super-horst ! we really appreciate that. If u want u can open the pr and we can help test it and write some test cases for it

**Comment by recapitalverb** [comment]
Seems like the RFC is merged! 🎉 Should this issue be closed then?

**Comment by GustavoKatel** [comment]
Yes! For now you need to use the main branch. We will issue a new release once all deps are ready to use tokio 0.3 :balloon:
